app/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required
from app.main.forms import LoginForm
from app.models import User, Category, MenuItem, Settings, MenuOrder
from app import bcrypt, db

main = Blueprint('main', __name__)

settings = Settings.query.first()

@main.route('/')
def index():
	categories = Category.query.all()
	foods = MenuItem.query.filter_by(available=1).all()
	food_ids = []

	for food in foods:
		food_ids.append(food.id)

	return render_template("index.html",
							foods=foods,
							categories=categories,
							settings=settings,
							food_ids=food_ids)

@main.route('/order/status')
def status_order():
	return render_template("status.html", settings=settings)

@main.route('/order/status/<order_id>')
def status_order_by_id(order_id):
	return render_template("status_by_id.html", settings=settings)

@main.route("/login", methods=["GET", "POST"])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.index'))
		else:
			flash("Login Failed! Please check your Email and Password", 'danger')
	return render_template("login.html", title="User Login", form=form)

@main.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.index'))

app/templates/index.html
{% extends 'layout.html' %}
{% block content %}

{% if current_user.is_authenticated %}
<h1>Welcome {{ current_user.username }}</h1>
{% endif %}

<div class="row">
    <div class="col-md-6 col-sm-12">
        <div class="card mt-4 p-5 mb-5">
            <h2>Foods available
                <button id="make_order" class='float-right btn btn-primary'>Make Order</button></h2>

            {% if foods %}
            <div id="item_list">
                <ul class="list-group mb-5 mt-5">
                    {% for food in foods %}

                    <li class="list-group-item">
                        {{ food.name }} - {{ food.price }} {{ settings.currency_sign }}
                        <span class="float-right">(<b>Quantity:</b> {{ food.quantity }})</span>
                    </li>

                    {% endfor %}
                </ul>
            </div>
            <div id="item_list_form" style="display: none;">
                <form id="makeOrderForm">
                    <ul class="list-group mt-5">
                        {% for food in foods %}
                        <div class="form-group">
                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value=""
                                        id="foodCheck-{{ food.id }}">
                                    <label class="form-check-label" for="foodCheck-{{ food.id }}">
                                        {{ food.name }} - <span data-originalprice="{{ food.price }}"
                                            id="foodPrice-{{ food.id }}">{{ food.price }}</span>
                                        {{ settings.currency_sign }}
                                        <input type="number" class="form-control form-control-sm" required
                                            placeholder="Quantity" id="changeQuantity-{{ food.id }}"
                                            style="display: none;" value="{{ food.quantity }}" min="1">
                                    </label>
                                </div>
                            </li>
                        </div>

                        {% endfor %}
                    </ul>
                    <div class="form-group">
                        <input type="text" class="form-control" required placeholder="Enter Your Name"
                            id="customer_name">
                    </div>
                    <input type="submit" class="btn btn-block btn-primary" value="Submit Order">
                </form>
            </div>
            {% else %}
            <p>If you are an admin, go to admin panel and add menu items</p>
            {% endif %}
        </div>
    </div>

    <div class="col-md-6 col-sm-12">
        <div class="card p-5 mb-5 mt-4">
            <h2>Browser Menu by Category</h2>
            {% if categories %}
            <!-- Accordion Using List Group -->
            <div id="accordion">
                <div class="panel list-group mt-5">

                    {% for category in categories %}
                    <a href="#category{{ category.id }}" data-parent="#accordion" data-toggle="collapse"
                        class="list-group-item">
                        {{ category.category_name }}
                    </a>
                    <div class="collapse" id="category{{ category.id }}">
                        <ul class="list-group mb-2 mt-2">
                            {% if category.items %}
                            {% for item in category.items %}
                            <li class="ml-3 list-group-item">
                                {{ item.name }} ({{ item.price }} {{ settings.currency_sign }})
                                {% if item.available %}
                                <span class="float-right badge badge-success">Available</span>
                                {% else %}
                                <span class="float-right badge badge-danger">Not Available</span>
                                {% endif %}
                            </li>
                            {% endfor %}
                            {% else %}
                            <li class="ml-3 list-group-item text-center">
                                No items available at this moment!
                            </li>
                            {% endif %}
                        </ul>
                    </div>

                    {% endfor %}
                </div>
            </div>
            {% else %}
            <p>If you are an admin, go to admin panel and add menu categories</h3>
                {% endif %}
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="statusModalCenter" tabindex="-1" role="dialog" aria-labelledby="statusModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span id="closeModal" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalBody">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" id="orderStatusButton" class="btn btn-primary btn-block">View Order Status</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>
    $("#make_order").click(function () {
        const buttonClassName = $(this).attr("class")

        if (buttonClassName == "float-right btn btn-primary") {
            $(this).removeClass("float-right btn btn-primary");
            $(this).addClass("float-right btn btn-danger");
            $(this).text("Cancel");

            $("#item_list").hide();
            $("#item_list_form").show();
        }
        else {
            $(this).removeClass("float-right btn btn-danger");
            $(this).addClass("float-right btn btn-primary");
            $(this).text("Make Order");

            $("#item_list").show();
            $("#item_list_form").hide();
        }
    })

    var food_ids = JSON.parse("{{food_ids}}")
    food_ids.forEach(function (food_id, index) {
        $(`#foodCheck-${food_id}`).on('change', (event) => {
            let priceSpan = $(`#foodPrice-${food_id}`);
            $(`#changeQuantity-${food_id}`).toggle();
            $(`#changeQuantity-${food_id}`).val("1");
            priceSpan.text(priceSpan.data('originalprice'));
        });

        $(`#changeQuantity-${food_id}`).on('keyup', (event) => {
            let quantity = event.target.value;
            let priceSpan = $(`#foodPrice-${food_id}`);
            let oldPrice = priceSpan.data('originalprice');
            let newPrice = parseInt(oldPrice) * quantity;
            priceSpan.text(newPrice);
        })
    })


    // submit order handler
    $("#makeOrderForm").on('submit', (event) => {
        event.preventDefault();
        // get all the inputs into an array.
        var $inputs = $('#makeOrderForm :input');
        var elementIds = []
        $inputs.each(function () {
            const elementId = $(this).attr('id');
            if (elementId !== undefined) {
                elementIds.push(elementId)
            }
        });

        var submitData = {}
        submitData['item'] = []
        elementIds.forEach(element => {
            if (element === "customer_name") {
                submitData['customer_name'] = $(`#${element}`).val();
            }
            else {
                const items = {}
                if (element.startsWith('foodCheck')) {
                    items['food_checked'] = $(`#${element}`).is(":checked");
                    items['food_id'] = $(`#${element}`).attr('id');
                }
                else {
                    items['quantity'] = $(`#${element}`).val();
                }
                submitData['item'].push(items)
            }
        })
        const newArr = []
        submitData['item'].forEach((item, index) => {
            const newDict = {}
            if (index % 2 === 1) {
                newDict['food_checked'] = submitData['item'][index - 1]['food_checked']
                newDict['food_id'] = submitData['item'][index - 1]['food_id']
                newDict['quantity'] = item['quantity']
                newArr.push(newDict)
            }

        })

        submitData['item'] = newArr

        const request = new XMLHttpRequest();
        request.open("POST", "/api/orders")
        request.setRequestHeader("Content-Type", "application/json");
        request.onload = () => {
            const responseData = JSON.parse(request.responseText);
            if (responseData.status == "OK") {
                $('#statusModalCenter').modal('show');
                $("#modalTitle").text("Congratulations!");
                $("#modalBody").html(`<p>Your order submitted successfully!</p><p><b>Order ID : ${responseData.response.order_id}</b></p><p>Please note your Order ID to check your order status!</p>`);
                $("#orderStatusButton").click(() => {
                    const order_id = responseData.response.order_id;
                    url_status_order = `/order/status/${order_id}`;
                    window.location.assign(url_status_order)
                })
            }
            else{
                $('#statusModalCenter').modal('show');
                $("#modalTitle").text("Oops!");
                $("#modalBody").html(`<p>Your order could not be created! Please try again!</p>`);
                $("#orderStatusButton").hide();
            }
            $("#closeModal").click(() => {
                window.location.reload(false);
            })
        }
        submitData = JSON.stringify(submitData);
        request.send(submitData);
        return false;

    })

</script>
{% endblock %}

app/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 

    <title>Restaurant Management</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Restaurant Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.status_order') }}">Order Status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Menu Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        {% if not current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                            </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">Admin Panel</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <main class="container mt-5">
        {% block content %}
        {% endblock %}
    </main>







    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <!-- Custom javascripts -->
    {% block scripts %}
    {% endblock %}
</body>

</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">User Login</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class = "form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="#">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>

{% endblock content %}

app/templates/status.html
{% extends 'layout.html' %}
{% block content %}

<div class="row">
    <div class="col mx-auto col-md-6">
        <form id="checkOrderStatus">

            <div class="form-group">
                <input type="number" class="form-control" required placeholder="Order ID" id="orderId">
            </div>

            <input type="submit" class="btn btn-block btn-primary" value="Check Status">
        </form>
    </div>
</div>

<div class="row mt-5 mb-5" id="orderStatus">
    <div class="col mx-auto col-md-6">
        <h4 id="errorMessage" style="display: none;"></h4>
        <table
            id="orderStatusTable"
            class="table table-striped table-bordered table-hover"
            style="margin-bottom: 0px !important; display: none;">
            <thead>
                <tr>
                    <th colspan="2" scope="col" id="statusOrderId" class="text-center">Order - 12</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name</td>
                    <td id="statusOrderCustomerName">Sojib</td>
                </tr>
                <tr>
                    <td>Last Updated</td>
                    <td id="statusOrderUpdated">18-08-2020 08:27 PM</td>
                </tr>
                <tr>
                    <td>Estimated Waiting Time</td>
                    <td id="statusOrderWaitTime">10 Minutes</td>
                </tr>
                <tr>
                    <td>Ready</td>
                    <td id="statusOrderReady">Not yet</td>
                </tr>
                <tr>
                    <td>Completed</td>
                    <td id="statusOrderCompleted">Not yet</td>
                </tr>
                <tr>
                    <td>Total Cost</td>
                    <td id="statusOrderCost">450</td>
                </tr>
            </tbody>
        </table>

        <table
            id="orderStatusTableItems"
            class="table table-striped table-bordered table-hover mt-5"
            style="margin-bottom: 0px !important; display: none;">
            <thead>
                <tr>
                    <th colspan="2" class="text-center">Items</th>
                </tr>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
    $("#checkOrderStatus").on('submit', () => {
        const orderId = $("#orderId").val();

        const request = new XMLHttpRequest();
        request.open("POST", "/api/status/order")
        request.setRequestHeader("Content-Type", "application/json");
        request.onload = () => {
            const responseData = JSON.parse(request.responseText);

            if (responseData.status == "OK") {
                $("#orderStatusTable").show();
                $("#errorMessage").hide();
                $("#statusOrderId").text(`Order - ${responseData.response.order_id}`);
                $("#statusOrderCustomerName").text(responseData.response.customer_name);
                $("#statusOrderUpdated").text(responseData.response.updated);
                $("#statusOrderWaitTime").text(responseData.response.wait_time);
                $("#statusOrderReady").html(responseData.response.is_ready == "Yes" ? "<i style='color: green' class='fa fa-check'>&nbsp;</i>Yes" : "<i style='color: red' class='fa fa-times'>&nbsp;</i>Not Yet");
                $("#statusOrderCost").text(responseData.response.order_cost);
                $("#statusOrderCompleted").html(responseData.response.is_complete == "Yes" ? "<i style='color: green' class='fa fa-check'>&nbsp;</i>Yes" : "<i style='color: red' class='fa fa-times'>&nbsp;</i>Not Yet");
                if (responseData.response.items.length>1){
                    $("#orderStatusTableItems tbody").html("");
                    $("#orderStatusTableItems").show();
                    responseData.response.items.forEach(item => {
                        const row_html = `<tr><td>${item.item_name}</td><td>${item.quantity}</td></tr>`
                        $("#orderStatusTableItems tbody").append(row_html)
                    })
                }
                else{
                    $("#orderStatusTableItems tbody").html("");
                    $("#orderStatusTableItems").show();
                    const row_html = `<tr><td colspan="2" class="text-center">No Items found in this order!</td></tr>`
                    $("#orderStatusTableItems tbody").append(row_html)
                }
            }
            else {
                $("#orderStatusTable").hide();
                $("#errorMessage").show();
                $("#errorMessage").text(responseData.message);
            }
        }

        submitData = JSON.stringify({
            "order_id": orderId
        });

        request.send(submitData);
        return false;
    })

</script>
{% endblock %}

app/templates/status_by_id.html
{% extends 'layout.html' %}
{% block content %}

<div class="row mt-5 mb-5" id="orderStatus">
    <div class="col mx-auto col-md-6">
        <h4 id="errorMessage" style="display: none;"></h4>
        <table
            id="orderStatusTable"
            class="table table-striped table-bordered table-hover"
            style="margin-bottom: 0px !important; display: none;">
            <thead>
                <tr>
                    <th colspan="2" scope="col" id="statusOrderId" class="text-center">Order - 12</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name</td>
                    <td id="statusOrderCustomerName">Sojib</td>
                </tr>
                <tr>
                    <td>Last Updated</td>
                    <td id="statusOrderUpdated">18-08-2020 08:27 PM</td>
                </tr>
                <tr>
                    <td>Estimated Waiting Time</td>
                    <td id="statusOrderWaitTime">10 Minutes</td>
                </tr>
                <tr>
                    <td>Ready</td>
                    <td id="statusOrderReady">Not yet</td>
                </tr>
                <tr>
                    <td>Completed</td>
                    <td id="statusOrderCompleted">Not yet</td>
                </tr>
                <tr>
                    <td>Total Cost</td>
                    <td id="statusOrderCost">450</td>
                </tr>
            </tbody>
        </table>

        <table
            id="orderStatusTableItems"
            class="table table-striped table-bordered table-hover mt-5"
            style="margin-bottom: 0px !important; display: none;">
            <thead>
                <tr>
                    <th colspan="2" class="text-center">Items</th>
                </tr>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>


    const request = new XMLHttpRequest();
    request.open("POST", "/api/status/order")
    request.setRequestHeader("Content-Type", "application/json");
    request.onload = () => {
        const responseData = JSON.parse(request.responseText);

        if (responseData.status == "OK") {
            $("#orderStatusTable").show();
            $("#errorMessage").hide();
            $("#statusOrderId").text(`Order - ${responseData.response.order_id}`);
            $("#statusOrderCustomerName").text(responseData.response.customer_name);
            $("#statusOrderUpdated").text(responseData.response.updated);
            $("#statusOrderWaitTime").text(responseData.response.wait_time);
            $("#statusOrderReady").html(responseData.response.is_ready == "Yes" ? "<i style='color: green' class='fa fa-check'>&nbsp;</i>Yes" : "<i style='color: red' class='fa fa-times'>&nbsp;</i>Not Yet");
            $("#statusOrderCost").text(responseData.response.order_cost);
            $("#statusOrderCompleted").html(responseData.response.is_complete == "Yes" ? "<i style='color: green' class='fa fa-check'>&nbsp;</i>Yes" : "<i style='color: red' class='fa fa-times'>&nbsp;</i>Not Yet");
            if (responseData.response.items.length>1){
                $("#orderStatusTableItems tbody").html("");
                $("#orderStatusTableItems").show();
                responseData.response.items.forEach(item => {
                    const row_html = `<tr><td>${item.item_name}</td><td>${item.quantity}</td></tr>`
                    $("#orderStatusTableItems tbody").append(row_html)
                })
            }
            else{
                $("#orderStatusTableItems tbody").html("");
                $("#orderStatusTableItems").show();
                const row_html = `<tr><td colspan="2" class="text-center">No Items found in this order!</td></tr>`
                $("#orderStatusTableItems tbody").append(row_html)
            }
        }
        else {
            $("#orderStatusTable").hide();
            $("#errorMessage").show();
            $("#errorMessage").text(responseData.message);
        }
    }
    submitData = JSON.stringify({
        "order_id": window.location.pathname.substring(window.location.pathname.lastIndexOf('/') + 1)
    });

    request.send(submitData);

</script>
{% endblock %}